language: python

python:
  - "3.4"

install:
  # Install Ruby
  - rvm install 2.2.3
  - rvm use 2.2.3 --default
  - gem install bundler

  # Install Python dependencies
  - pip install -r requirements3.txt
  # Install Ruby dependencies
  - bundle install

script:
  - nosetests
