name:       James Fogarty
baseurl:    /~jfogarty

brandimage: ''
brandtext:  'James Fogarty'

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Publications'
      link: 'publications.html'

exclude:
  # Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
