name:       James Fogarty
baseurl:    /~jfogarty

brandimage: ''
brandtext:  'James Fogarty'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Publications'
      link: 'publications.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
