name:       James Fogarty
baseurl:    /~jfogarty

brandimage: ''
brandtext:  'James Fogarty'

exclude:
  # Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
